version: '3'
services:
  app:
    image: node:20
    volumes:
      - .:/app
    working_dir: /app
    command: /bin/sh -c "yarn install && yarn start:dev"
    environment:
      - SUPABASE_PUBLIC_KEY=${SUPABASE_PUBLIC_KEY}
      - SUPABASE_SERVICE_ROLE_KEY=${SUPABASE_SERVICE_ROLE_KEY}
      - SUPABASE_URL=${SUPABASE_URL}
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    ports:
      - 3000:3000
    depends_on:
      - redis

  redis:
    image: redis:latest
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data

volumes:
  redis-data:
