name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Execute remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: chatserver.chatbutler.ai
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd promptsandbox.io
          git pull
          yarn workspace @chatbutler/shared build
          if [ -d "packages/server/dist" ]; then rm -r packages/server/dist; fi
          yarn workspace @chatbutler/server build
          pm2 restart ecosystem.config.js
