name: Deploy
on:
  push:
    branches:
      - main  # Or your default branch
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Execute remote ssh commands
      uses: appleboy/ssh-action@master
      with:
        host: chatserver.chatbutler.ai
        username: root
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          cd promptsandbox.io
          git pull
          yarn workspace @chatbutler/shared build
          yarn workspace @chatbutler/server build
          pm2 restart ecosystem.config.js
